version: "3.7"
services:
  mongodb:
    image: mongo:5
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      "MONGO_INITDB_ROOT_USERNAME": ${MONGODB_USERNAME}
      "MONGO_INITDB_ROOT_PASSWORD": ${MONGODB_PASSWORD}
    restart: '${RESTART_POLICY:-on-failure:10}'
    volumes:
      - ${MONGODB_DATA_LOCATION:-mongodata}:/data/db
  redis:
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: '${RESTART_POLICY:-on-failure:10}'
    volumes:
      - ${REDIS_DATA_LOCATION:-redisdata}:/data
volumes:
  mongodata: null
  redisdata: null
