name: Build
on:
  workflow_dispatch:
    inputs:
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      build: ${{ github.run_number }}
    steps:
      - run: echo build number ${{ github.run_number }}
  #--------------------------------------------------------------------
  #
  #--------------------------------------------------------------------
  build_docker_identity:
    name: Service.Identity
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      #----------------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #----------------------------------------------------------------
      - name: Update appsettings.json Version.Build
        uses: jossef/action-set-json-field@v2
        with:
          file: ./src/Service.Identity/appsettings.json
          field: Version.Build
          value: ${{ needs.prepare.outputs.build }}
      #----------------------------------------------------------------
      - run: cat ./src/Service.Identity/appsettings.json
      #----------------------------------------------------------------
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "🚀 Build"
        working-directory: ./src
        run: docker build -t netcore-identity:${{ needs.prepare.outputs.build }} -f Service.Identity/Dockerfile .
      - run: docker push dorofiykolya/netcore-identity:${{ needs.prepare.outputs.build }}
      #----------------------------------------------------------------
  #--------------------------------------------------------------------
  #
  #--------------------------------------------------------------------
